# Generated by Django 5.2.7 on 2025-10-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('owner', models.CharField(max_length=150)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('health', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', max_length=10)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('on_hold', 'On hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('deleted', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
    ]
