# Generated by Django 5.2.7 on 2025-10-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_milestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('pm', 'Project Manager'), ('dev', 'Developer'), ('qa', 'QA'), ('other', 'Other')], default='other', max_length=50)),
                ('capacity_percent', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('projects', models.ManyToManyField(related_name='team', to='projects.project')),
            ],
        ),
    ]
