# Generated by Django 5.2.7 on 2025-10-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_recentactivityevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='milestone',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
