version: '3.9'

services:
  db:
    image: postgres:15
    container_name: pm_postgres
    environment:
      POSTGRES_DB: pm_db
      POSTGRES_USER: pm_user
      POSTGRES_PASSWORD: pm_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pm_network

  backend:
    image: vasmoul/project-dashboard-backend:latest
    container_name: pm_backend
    command: >
      sh -c "python manage.py migrate &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_NAME=pm_db
      - DATABASE_USER=pm_user
      - DATABASE_PASSWORD=pm_password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    networks:
      - pm_network

  frontend:
    build:
      context: ./frontend   # path to your local frontend folder
      dockerfile: Dockerfile
    container_name: pm_frontend
    ports:
      - "3000:80"
    networks:
      - pm_network
    environment:
      - REACT_APP_API_URL=http://backend:8000
volumes:
  pgdata:

networks:
  pm_network:
    driver: bridge
